language: ruby
os:
  - linux
  - osx
rvm:
  - ruby-head
  - 2.1.7
  - 2.2.3
  - 2.3.0
  - jruby-9000
before_install:
  - gem install bundler -v 1.10.5
install: bin/setup
script:
  - cd ext/argon2_wrap/ && make test && cd ../..
  - rake test
  - rake rubocop
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - rvm: ruby-head
addons:
  code_climate:
    repo_token: 28e3d5d04f4ec87d0899784e6aecc13d7787343b2634b3c94fc1216993d443c2
